/* NODE_PATH points to temporary dependencies; no project install required. */
const {JSDOM} = require('jsdom');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const {execFileSync} = require('node:child_process');
const html = fs.readFileSync('index.html','utf8').replace(/<script[^>]*>[\s\S]*?<\/script>/g,'');
const dom = new JSDOM(html,{url:'https://test.local',runScripts:'outside-only'});
const w = dom.window;
w.scrollTo = () => {}; w.HTMLElement.prototype.scrollIntoView = () => {};
w.confirm = () => true;
const blobs = []; w.URL.createObjectURL = blob => {blobs.push(blob); return 'blob:test';}; w.URL.revokeObjectURL = () => {};
w.HTMLAnchorElement.prototype.click = () => {};
const vm = require('node:vm');
for (const file of ['penyelia-seed.js','app.js','penyelia.js']) vm.runInContext(fs.readFileSync(file,'utf8'),dom.getInternalVMContext());
const run = code => vm.runInContext('{'+code+'}',dom.getInternalVMContext());
run('init()');
const independent = JSON.parse(execFileSync('python',['verify_sources.py'],{encoding:'utf8'}));
assert.equal(run('state.records.penyeliaPelajar.length'), independent.groups);
assert.equal(run('state.records.penyeliaPelajar.flatMap(g=>g.pelajar).length'), independent.students);
assert.equal(run('state.records.penyeliaPelajar.filter(g=>!g.pelajar.length).length'),5);
assert.equal(run('state.records.penyeliaPelajar.flatMap(g=>g.pelajar).filter(p=>p.statusKhas==="graduasi").length'),2);
assert.equal(run('state.records.penyeliaPelajar.flatMap(g=>g.pelajar).filter(p=>p.statusKhas==="diberhentikan").length'),2);
run(`WORKSPACES.filter(w=>!w.nested).forEach(w=>{go(w.id); if(w.columns.some(c=>c.key==='nama')) { const r=state.records[w.id][0]; if(r) {startEdit(w.id+'|'+r.id); if(!document.querySelector('label [data-field="'+identityKey(w)+'"]')) throw Error(w.id); cancelEdit();}}});`);
assert.equal(run('normalizedMatric({noPelajar:"860927565833"})'),'');
assert.equal(run('normalizedMatric({nama:"A (p12345)"})'),'P12345');
run(`go('senat'); const r=state.records.senat[0]; startEdit('senat|'+r.id); document.querySelector('[data-field="nama"]').value='Edited'; document.querySelector('[data-field="noPelajar"]').value='P55555'; requestSave('senat|'+r.id); document.getElementById('confirmSave').click();`);
assert.equal(run('state.records.senat[0].noPelajar'),'P55555');
assert.ok(!w.document.querySelector('.student-name').textContent.includes('('));
run(`ui.query.senat='P55555'; render();`);
assert.equal(w.document.querySelectorAll('tbody tr[data-record]').length,1);
run(`exportWorkspace('senat'); exportWorkspace('penyeliaPelajar');`);
assert.equal(blobs.length,2);
run(`go('penyeliaPelajar')`);
assert.equal(w.document.querySelectorAll('.penyelia-panel').length,34);
assert.equal(w.document.querySelectorAll('.penyelia-panel.is-open').length,29);
assert.equal(w.document.querySelectorAll('.lepas-panel').length,0);
w.document.querySelector('[data-seg="semua"]').click();
assert.equal(w.document.querySelectorAll('.lepas-panel').length,3);
w.document.querySelector('[data-toggle-lepas]').click();
assert.equal(w.document.querySelectorAll('.lepas-panel.is-open').length,1);
run(`focusRecord('csv-student-P108824')`);
assert.ok(w.document.querySelector('[data-record="csv-student-P108824"]'));
run(`openSupervisorDrawer(); document.getElementById('supervisorName').value='Cancel'; closeDrawer();`);
assert.equal(run('state.records.penyeliaPelajar.length'),34);
run(`openSupervisorDrawer(); document.getElementById('supervisorName').value='New supervisor'; document.getElementById('saveSupervisor').click();`);
assert.equal(run('state.records.penyeliaPelajar.length'),35);
run(`const parent=state.records.penyeliaPelajar.at(-1); openPelajarDrawer(parent.id); document.getElementById('dNama').value='New student'; document.getElementById('dNoPelajar').value='P99999'; document.getElementById('savePelajar').click();`);
assert.equal(run('state.records.penyeliaPelajar.at(-1).pelajar.length'),1);
run(`const g=state.records.penyeliaPelajar.at(-1); confirmNestedDelete(g,g.pelajar[0]); document.getElementById('confirmNestedDelete').click();`);
assert.equal(run('state.trash[0].kind'),'student');
run('restoreTrash(state.trash[0].id)');
assert.equal(run('state.records.penyeliaPelajar.at(-1).pelajar.length'),1);
run(`const g=state.records.penyeliaPelajar.at(-1); confirmNestedDelete(g); document.getElementById('confirmNestedDelete').click(); restoreTrash(state.trash[0].id);`);
assert.equal(run('state.records.penyeliaPelajar.at(-1).pelajar.length'),1);
run(`const p=state.records.penyeliaPelajar.at(-1).pelajar[0]; p.statusKhas='graduasi'; p.tarikhStatus='2026-09-01'; syncGraduan(p); syncGraduan(p);`);
assert.equal(run('state.records.graduan.filter(g=>g._syncOrigin).length'),1);
assert.ok(run('state.records.graduan.at(-1).penyelia').includes('New supervisor'));
run(`state.records.graduan.push({id:'manual',nama:'Manual (P99999)',catatan:'Keep'}); const p=state.records.penyeliaPelajar.at(-1).pelajar[0]; p.statusKhas=''; syncGraduan(p);`);
assert.equal(run('state.records.graduan.filter(g=>g._syncOrigin).length'),0);
assert.equal(run('state.records.graduan.find(g=>g.id==="manual").catatan'),'Keep');
run(`const p=state.records.penyeliaPelajar.at(-1).pelajar[0]; p.statusKhas='graduasi'; syncGraduan(p);`);
assert.equal(run('state.records.graduan.filter(g=>g._syncOrigin).length'),0);
run(`ui.penyeliaSession='2/2025-2026';`);
assert.equal(run('recentSessions().join(",")'),'1/2023-2024,2/2023-2024,2/2025-2026');
assert.equal(run('snapshot(state.records.penyeliaPelajar[1].pelajar[0],"2/2022-2023").semesterPengajian'),'15');
run(`openPelajarDrawer('csv-supervisor-2','csv-student-P93318'); document.getElementById('savePelajar').click();`);
assert.equal(run('state.records.penyeliaPelajar[1].pelajar[0].sejarahSemester[0].semesterPengajian'),'15');
run(`openPelajarDrawer('csv-supervisor-9','csv-student-P86119'); document.getElementById('savePelajar').click();`);
assert.equal(w.document.querySelector('#drawerOverlay'),null,'undated historic graduate can be edited');
assert.equal(run('state.records.graduan.filter(g=>g._syncOrigin).length'),0);
// Legacy subset migration: no reset, no overwritten statuses or notes, explicit merge.
run(`seedData(); state.records.penyeliaPelajar[0].pelajar[0].nama='USER EDIT'; const before=JSON.stringify(state.records); prepareStudentData(true); previewPenyeliaImport(); document.getElementById('mergeImport').click();`);
assert.equal(run('state.records.penyeliaPelajar[0].pelajar[0].nama'),'USER EDIT');
assert.equal(run('state.records.penyeliaPelajar.flatMap(g=>g.pelajar).length'),95);
assert.equal(run('state.records.penyeliaPelajar.length'),34);
assert.equal(run('state.records.penyeliaPelajar[1].pelajar[0].statusKhas'),'graduasi');
assert.ok(run('!!state.records.penyeliaPelajar[0].pelajar[0].csvSources'));
run('mergePenyeliaImport(importPlan())');
assert.equal(run('state.records.penyeliaPelajar.flatMap(g=>g.pelajar).length'),95);
// Opt-in adoption preserves backup, lifecycle defaults, and transfers without duplication.
run(`const p=state.records.penyeliaPelajar.flatMap(g=>g.pelajar).find(p=>p.noPelajar==='P168677'); const g=state.records.penyeliaPelajar.find(g=>g.pelajar.includes(p)); g.pelajar=g.pelajar.filter(x=>x!==p); state.records.penyeliaPelajar.find(g=>g.id==='csv-supervisor-1').pelajar.push(p); p.nama='LOCAL'; const plan=importPlan(); plan.adopt=[plan.matches.findIndex(x=>x.incoming.noPelajar==='P168677')]; mergePenyeliaImport(plan);`);
assert.equal(run('state.records.penyeliaPelajar.flatMap(g=>g.pelajar).filter(p=>p.noPelajar==="P168677").length'),1);
assert.ok(run('state.records.penyeliaPelajar.find(g=>g.pelajar.some(p=>p.noPelajar==="P168677")).namaPenyelia').includes('ASIF'));
assert.equal(run('state.records.penyeliaPelajar.flatMap(g=>g.pelajar).find(p=>p.noPelajar==="P168677").importBackups.at(-1).record.nama'),'LOCAL');
run(`const g=state.records.penyeliaPelajar.find(g=>g.pelajar.some(p=>p.noPelajar==='P168677')); const p=g.pelajar.find(p=>p.noPelajar==='P168677'); p.id='legacy-random-id'; confirmNestedDelete(g,p); document.getElementById('confirmNestedDelete').click(); mergePenyeliaImport(importPlan());`);
assert.equal(run('state.records.penyeliaPelajar.flatMap(g=>g.pelajar).filter(p=>p.noPelajar==="P168677").length'),0,'archived legacy matric must not resurrect');
console.log('PASS: independent three-source audit 34 supervisors / 95 unique / 275 occurrences; source preservation and precedence; 91 active / 4 past; browser migration and opt-in transfer; identity, drawers, sync, semester regressions.');
dom.window.close();
